[project]
authors = [{name = "Ben warren", email = "polarisinc@gmail.com"}]
dependencies = ["bientropy>=1.1.4,<2", "requests>=2.34.2,<3", "pandas>=3.0.5,<4", "matplotlib>=3.11.1,<4", "seaborn>=0.13.2,<0.14", "aiohttp>=3.14.3,<4", "asyncio>=4.0.0,<5", "biopython>=1.88,<2", "multiprocess>=0.70.19,<0.71"]
name = "gabi"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-options]
no-binary = ["bientropy"]

[tool.pixi.pypi-dependencies]
gabi = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
ipykernel = ">=7.3.0,<8"

[tool.pixi.build-dependencies]
setuptools = ">=84.0.0,<85"

